const fs = require("fs");
const path = require("path");

const sourceDir = path.join(__dirname, "SourceCsvs");
const files = fs.readdirSync(sourceDir).filter((f) => f.endsWith(".csv")).sort();

const decks = files.map((f) => {
  const name = path.basename(f, ".csv");
  const id = name.toLowerCase().replace(/\s+/g, "-");
  return {
    id,
    name,
    file: "SourceCsvs/" + f,
  };
});

const manifest = {
  buildTime: Date.now(),
  decks,
};

fs.writeFileSync(
  path.join(__dirname, "manifest.json"),
  JSON.stringify(manifest, null, 2)
);

// Generate sw-version.js so the service worker updates whenever build.js is run
const cacheFiles = [
  "./index.html",
  "./styles.css",
  "./app.js",
  "./supabase-config.js",
  "./manifest.json",
  "./sw.js",
  ...decks.map((d) => "./" + d.file),
];

const swVersion = `// Auto-generated by build.js — do not edit
const CACHE_VERSION = "${manifest.buildTime}";
const CACHE_FILES = ${JSON.stringify(cacheFiles, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, "sw-version.js"), swVersion);

console.log("Generated manifest.json with " + decks.length + " deck(s):");
decks.forEach((d) => console.log("  " + d.name + " (" + d.file + ")"));
console.log("Generated sw-version.js (cache version: " + manifest.buildTime + ")");
