// Auto-generated by build.js — do not edit
const CACHE_VERSION = "1776084368406";
const CACHE_FILES = [
  "./index.html",
  "./styles.css",
  "./app.js",
  "./supabase-config.js",
  "./manifest.json",
  "./sw.js",
  "./SourceCsvs/AI Design Patterns.csv",
  "./SourceCsvs/French.csv",
  "./SourceCsvs/Indo Eng-Ind.csv",
  "./SourceCsvs/Indo Ind-Eng.csv",
  "./SourceCsvs/Indonesian.csv",
  "./SourceCsvs/Spanish.csv"
];
